version: 0.2

phases:
  install:
    commands:
    - apt-get -y update
    - pip install --upgrade pip
    - pip install prowler==$prowler_version
  pre_build:
    commands:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip -u awscliv2.zip
    - ./aws/install --update
    - prowler -v
  build:
    commands:
    - prowler aws -f $default_region
artifacts:
  files:
  - "**/*"
  name: prowlerCheck-$(date +%Y-%m-%d)




