version: 0.2

phases:
  install:
    commands:
    - pip install prowler==$prowler_version
  pre_build:
    commands:
    - prowler -v
  build:
    commands:
    - prowler aws -f $default_region
artifacts:
  files:
  - "**/*"
  name: prowlerCheck-$(date +%Y-%m-%d)




